### ISSUE TITLE
Enchantments cause falses due to new 1.21 attributes and PacketEvents unable to read enchants

### ISSUE THREAD

**Issue by Devuxious** [GrimAnticheat/Grim#1583]
### Describe the false positive and how to replicate it

Here are some issues I encountered within the first five minutes of using this anticheat:

- Using a trident in water results in a simulation flag.
- Swimming with the Depth Strider enchantment also triggers a simulation flag.
- Using a pickaxe with any efficiency enchantment causes a fast break flag.

There are likely more issues, but I haven't had the chance to test further yet.

### Grim version

2.3.65

### Server version

Paper 1.21-38-master@1f5db50

### Plugins

CoreProtect, Delta (custom core), FastAsyncWorldEdit, PlaceholderAPI

**Comment by SamB440** [comment]
It's not ignoring them, it's because Mojang completely changed the calculations in 1.21

**Comment by Cats1337** [comment]
I've also found this issue. Efficiency sets off fastbreak alert, depth strider sets off simulation alert and drowns players. I tried to modify the config to help with it but to no avail. Packets clearly aren't being handled correctly.

**Comment by SamB440** [comment]
Please read what I said, it's not a packet issue, it's an issue with viaversion + Mojang changing everything to use attributes which also changed the movement calculations. My attribute-rework branch fixes this, but it is complicated to fix: https://github.com/GrimAnticheat/Grim/blob/16a90bb41db1841c9e821ed7352ecd109186e44a/src/main/java/ac/grim/grimac/utils/data/packetentity/PacketEntitySelf.java#L58-L78

**Comment by NUBBA12** [comment]
is there an ETA to the fix?

**Comment by Anthony01M** [comment]
> is there an ETA to the fix? How do I disable this

no ETA;
Follow these steps to disable FastBreak:
1. Go to punishments.yml
2. Search for - "FastBreak"
3. Replace - "FastBreak" with - "!FastBreak" (or just add a ! before FastBreak but people won't understand or even manage to do something weird and break their whole punishments config)
4. Restart your server

**Comment by NUBBA12** [comment]
Thanks!

**Comment by CatBang** [comment]
Now you can try the [latest build version of <attribute-rework>](https://github.com/GrimAnticheat/Grim/actions/runs/10333304179). I tested it on 1.21, and players have reported that many enchants misreporting issues have been fixed and can be used normally.

**Comment by g0ldyy** [comment]
Hey!
Trident with Riptide still not working.
FastBreak also still false flagging.
I'm running latest Grim commit.

Am I doing something wrong?

**Comment by carlodrift** [comment]
> Hey! Trident with Riptide still not working. FastBreak also still false flagging. I'm running latest Grim commit.
> 
> Am I doing something wrong?

https://github.com/GrimAnticheat/Grim/actions/runs/10333304179/artifacts/1798102852
